@startuml SpringFood

Address "1" -- "0..n" Account
Address "1" -u- "1" Order
Client "0..n" -- "1..1" Order
Worker "0..n" --- "0..1" Order
Order "1..n" -r- "1" OrderLine 
OrderLine "1" -- "0..n" Product
Product "1" -d- "0..n" ProductType
Product "1..n" -d- "0..n" Promotion

Class Address {
    - id : long
    - city : string
    - street : string
    - postal : int
    - owner : Account
    - isMain : boolean
}

Class Account {
    - name : String
    - phone : String
    - email : String
    - password : String
    - address : Address[]
}

Class Worker extends Account{
    - deliveryManager : boolean
    - orderManager : boolean
    - productManager : boolean
    - adminAccess : boolean
    - springfoodConfiguration : boolean
}

Class Client extends Account{

}

Class Order {
    - id : string
    - stripe : string
    - createdAt : LocalDateTime
    - orderTotal : long
    - paid : boolean
    - homeDelivery : boolean
    - deliveryWorker : Worker
    - isDelivered : boolean
    - deliveryAddress : Address
    - deliveryDateTime: LocalDateTime
    - orderLines : OrderLine[]
}

Class OrderLine {
    - id : long
    - order : Order
    - product : Product
    - quantity : int
    - lineTotal : long
}

Class Product {
    - id : long
    - name : String
    - description : String
    - stock : int
    - discount : byte
    - price : long
    - productTypes : ProductType[]
    - trackStock : boolean
    - isActive : boolean
    - promotion: long
}

Class Promotion {
    - id : long
    - product : long
}

Class ProductType {
    - id : long
    - name : String
    - description : String
}

@enduml